name: Trainings pipeline
on:
  workflow_dispatch:
  schedule:
    - cron:  "15 02 * * 1"

jobs:
  kerastuner:
    name: KerasTuner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Create artifact folder
        run: |
          mkdir -p data
          mkdir -p tmp
      - name: KerasTuner
        run: python tweety_bitcoin_psychic/pipe_kerastuner.py
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: assets
          path: data
          retention-days: 10

  train:
    needs: kerastuner
    name: Train new model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          name: assets
          path: data
      - name: Train new model
        run: python tweety_bitcoin_psychic/pipe_train.py
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: assets
          path: data
          retention-days: 10

  compare:
    needs: [kerastuner, train]
    name: Retrain & compare old model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Download last workflow artifacts
        continue-on-error: true
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: pipeline.yml
          workflow_conclusion: success
      - name: Download last job artifacts
        uses: actions/download-artifact@main
        with:
          name: assets
          path: data
      - name: Retrain & compare old model
        run: python tweety_bitcoin_psychic/pipe_compare.py
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: assets
          path: data
          retention-days: 10

  forecast:
    needs: [kerastuner, train, compare]
    name: Train best model
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Download last workflow artifacts
        continue-on-error: true
        uses: dawidd6/action-download-artifact@master
        with:
          workflow: pipeline.yml
          workflow_conclusion: success
      - name: Download last job artifacts
        uses: actions/download-artifact@main
        with:
          name: assets
          path: data
      - name: Train best model
        run: python tweety_bitcoin_psychic/pipe_forecast.py
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: assets
          path: data
          retention-days: 10

  twitter:
    # if: ${{ github.event_name == 'schedule' }}
    needs: [kerastuner, train, compare, forecast]
    name: Tweet forecast
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.15"
      - run: pip install -r requirements.txt
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          name: assets
          path: data
      - name: Tweet forecast
        run: python tweety_bitcoin_psychic/pipe_twitter.py
        